### ISSUE TITLE
Feedback Final Project UTS

### ISSUE THREAD

**Issue by aufaroot18** [dendisetiawan/Uts_Frontend_developer_dendisetiawan_0110219036#1]
Terima kasih sudah mengerjakan Final Project UTS.

Berikut aku sampaikan hasil feedback dan evaluasi Final Project UTS.

## Feedback Umum

- Set Repo ke Private.
- Aplikasi belum sesuai secara desain dan fungsionalitas.
- Aplikasi belum responsive.

## Perbaikan

- Component Global harusnya menggunakan data dari constant.
- Component Table belum berfungsi.
- Component Form belum berfungsi.

_Thanks, Aufa Billah._

**Comment by dendisetiawan** [comment]
Iya pak saya akui kesalahan saya pak
Mohon maaf kurang maksimal
Saya berharap bapak tidak marah dan tetap mau nerima saya menjadi mahasiswa
bapak di kelas Frontend

Terimakasih pak

Pada tanggal Jum, 20 Mei 2022 17:13, Aufa Billah ***@***.***>
menulis:

**Comment by aufaroot18** [comment]
Silahkan diperbaiki projeknya karena akan berlanjut sampai UAS.

**Comment by dendisetiawan** [comment]
Siap pak , minta do'anya pak semoga lancar semuanya pak

Pada tanggal Jum, 20 Mei 2022 20:06, Aufa Billah ***@***.***>
menulis:

**Comment by aufaroot18** [comment]
Aaamin.

**Comment by dendisetiawan** [comment]
Pak mohon maaf boleh minta buka slide yang kemaren kah pak?

Pada tanggal Jum, 20 Mei 2022 20:07, Dendi Setiawan <
***@***.***> menulis:
